envVars:
  API_BASE_URL: http://stg2-www.restorationhardware.com
  API_TIMEOUT: 10000
  NODE_ENV: development
  DEBUG: "*"
  REACT_APP_KEYCLOAK_URL: https://keycloak.internal.rhapsodysandbox3.net/auth
service:
  name: keycloak-react-demo
  internalPort: 3000
  apiversion: v1
  version: 0.0.1
  livenessProbe:
    path: /
  readinessProbe:
    path: /
replicaCount: 1
scaling:
  enabled: false
